name: Publish to NPM
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build job triggered by ${{ github.event_name }} event, branch ${{ github.ref }}"
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "[>] Cloned repository to runner"
      - run: echo "[>] Installing packages"
      - run: npm install
      - run: echo "[>] Running build script"
      - run: npm run build
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Publish job triggered by ${{ github.event_name }} event, branch ${{ github.ref }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
      - run: echo "[>] Installing packages"
      - run: npm install
      - run: echo "[>] Running build script"
      - run: npm run build
      - run: echo "[>] Publishing to NPM"
      - name: "Publish to NPM"
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_EUDOROS }}
      - run: echo "[>] Publishing to GitHub Package Registry"
      - name: "Publish to GitHub Package Registry"
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com"
